kind: Service
apiVersion: v1
metadata:
  name: bookstore
  labels:
    app: bookstore
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: bookstore
  type: NodePort
status:
  loadBalancer: {}
